# Generated by Django 4.1.7 on 2023-03-16 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='avto_rasmlar')),
                ('nomi', models.CharField(max_length=200)),
                ('yil', models.IntegerField()),
                ('manzil', models.CharField(max_length=200)),
                ('modeli', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=100)),
                ('pozitsiya', models.IntegerField()),
                ('egasi', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('izoh', models.TextField()),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategoriya')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
    ]
